# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75752e4b746f96b73e28453486b144bc9b8ba4f191ef7d95a13fe1d4d9f0c1b8079759e5d7c66e605bf231cc631621d93eccce95ed8b5b38630ecf20694e5355

test:
  secret_key_base: 6d8b584d87fda4bc107adeb4206e00b86a07969470e84ea4034da25ab23a2ad7e48fe0c4c0c1d0848df024e020e731bbeb0f9846234c7e56efe26a6e71e9bfdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
